{% set name = "napari-omero" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1650718c1923984f4df510dccb35d3d4ee80c8bfe28f61b3806460f0dbbffe8

build:
  entry_points:
    - napari-omero = napari_omero.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<=3.10
    - hatchling
    - hatch-vcs
  run:
    - napari >=0.4.3
    - omero-py
    - omero-rois
    - python >=3.7,<=3.10

test:
  imports:
    - napari_omero  # [not linux]
  commands:
    - pip list
    - pip check
    - xvfb-run -a python -c "import napari_omero"  # [linux]
    # the CLI does not have a --help option, it launches napari
    # and stays open - we use timeout to close it, but it throws a non-zero
    # exit code so we ignore it with `|| true`
    - timeout 30 xvfb-run -a napari-omero || true   # [linux]
    # - napari-omero  # [not linux]
  requires:
    - pip

about:
  home: https://github.com/tlambert03/napari-omero
  summary: napari/OMERO interoperability
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
